# config.py
import os

# Core system constants
VECTOR_DIMENSION = int(os.getenv("VECTOR_DIMENSION", 1024))
SHARD_COUNT = int(os.getenv("SHARD_COUNT", 8))
NETWORK_OVERHEAD = 0.02  # seconds
AES_KEY_SIZE = 256
DEFAULT_SIMILARITY_THRESHOLD = 0.75
MVCC_WRITE_LOCK_TIMEOUT = 5.0
MAX_BATCH_SIZE = 128
BLOCKCHAIN_DIFFICULTY = 2

# Logging configuration
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
